### ISSUE TITLE
[Raw Data] Sensor Calibration Data Format

### ISSUE THREAD

**Issue by Durant35** [Durant35/kitti_ros#19]
- [x] 数据示例
    ![image](https://user-images.githubusercontent.com/6770853/40602292-a287a1bc-628a-11e8-82e9-63dcb7339328.png)
- [x] [Coordinate Systems](https://github.com/LidarPerception/kitti_ros/issues/19#issuecomment-392433155)
- [x] [Camera-to-camera calibration](https://github.com/LidarPerception/kitti_ros/issues/19#issuecomment-392444147)
- [x] [Velodyne-to-camera registration](https://github.com/LidarPerception/kitti_ros/issues/19#issuecomment-392444384)
- [x] [GPS/IMU-to-Velodyne registration](https://github.com/LidarPerception/kitti_ros/issues/19#issuecomment-396870589)
- [x] [Example transformations](https://github.com/LidarPerception/kitti_ros/issues/19#issuecomment-779900539)

## 参考文献
```bibtex
@article{geiger2013vision,
  title={Vision meets robotics: The KITTI dataset},
  author={Geiger, Andreas and Lenz, Philip and Stiller, Christoph and Urtasun, Raquel},
  journal={The International Journal of Robotics Research},
  volume={32},
  number={11},
  pages={1231--1237},
  year={2013},
  publisher={Sage Publications Sage UK: London, England}
}
```

**Comment by Durant35** [comment]
## Coordinate Systems
> Sensor Setup #1

![image](https://user-images.githubusercontent.com/6770853/40600551-72fcb64a-6284-11e8-9b7e-eba79835960e.png)
+ 右手坐标系
    + 相机（x：右，y：下，z：前） 
    + 点云（x：前，y：左，z：上）
    + 惯导（x：前，y：左，z：上）

**Comment by Durant35** [comment]
## Camera-to-camera calibration
![image](https://user-images.githubusercontent.com/6770853/40600601-a0c4ea66-6284-11e8-9fff-3bd3f440196f.png)
+ ### 内参、畸变纠正
    + S_xx **(1x2)**：矫正前的图像xx的大小 
    + K_xx **(3x3)**：矫正前摄像机xx的校准矩阵 
    + D_xx **(1x5)**：矫正前摄像头xx的失真向量
+ ### 转换到相机坐标系`xx: `**00-03**
    + R_xx **(3x3)**：（外部）的旋转矩阵(从相机0到相机xx) 
    + T_xx **(3x1)**：（外部）的平移矢量(从相机0到相机xx) 
+ ### 转换到相机`xx: `**00-03**所在图像像素坐标系
    + S_rect_xx **(1x2)**：矫正后的图像xx的大小 
    + R_rect_xx **(3x3)**：纠正旋转矩阵(使图像平面共面)  **==>图像物理坐标系**
    + P_rect_xx **(3x4)**：矫正后的投影矩阵 **==>图像像素坐标系**
+ ### 如何应用？
![image](https://user-images.githubusercontent.com/6770853/41210689-c10365be-6d65-11e8-9772-23a21c22aba9.png)
![image](https://user-images.githubusercontent.com/6770853/41210744-134705f6-6d66-11e8-8ed4-7061e69b88b1.png)

![image](https://user-images.githubusercontent.com/6770853/41224650-8d88e53a-6d9f-11e8-9bbd-c39fc443c79a.png)

**Comment by Durant35** [comment]
## Velodyne-to-camera registration
![image](https://user-images.githubusercontent.com/6770853/40602686-16520ac8-628c-11e8-9a11-0267d2384edd.png)

+ ### Velodyne到相机坐标系`00`的外参
    + R：**(3x3)** 旋转矩阵 
    + T：**(3x1)** 平移向量 
    + delta_f：弃用 
    + delta_c：弃用
+ ### 如何应用？
![image](https://user-images.githubusercontent.com/6770853/40606085-d50a449e-6296-11e8-8d73-f93c59b0d6fd.png)

**Comment by Durant35** [comment]
## GPS/IMU-to-Velodyne registration
![image](https://user-images.githubusercontent.com/6770853/40602730-4265e774-628c-11e8-9a09-101e32d74347.png)
+ ### 如何应用？
![image](https://user-images.githubusercontent.com/6770853/41210894-c11c80f2-6d66-11e8-9725-a1c3dcfa73a3.png)
+ ### 点云坐标系下使用定位信息 https://github.com/Durant35/kitti_ros/issues/22
![image](https://user-images.githubusercontent.com/6770853/40961573-85dffc5c-68d5-11e8-8f79-11179de6af68.png)

**Comment by ReedGao** [comment]
请问这些信息你从哪里找的？devkit里面根本没有这些

**Comment by Durant35** [comment]
## Example transformations: [kitti_lidar_camera](https://github.com/Durant35/kitti_lidar_camera)
![image](https://user-images.githubusercontent.com/6770853/40602946-fba2d12a-628c-11e8-920a-d15d39d9e5e9.png)

+ ### 世界坐标系（Velodyne坐标系）转换到相机`xx`坐标系
+ ### 相机`xx`坐标系转换到图像物理坐标系
+ ### 图像物理坐标系转换到图像像素坐标系`xx: `**00-03**
![image](https://user-images.githubusercontent.com/6770853/40606085-d50a449e-6296-11e8-8d73-f93c59b0d6fd.png)
